# THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.
# BASED ON d:\Projects\Cube\ADCDecoder

# -mmcu=avr128db48 -B "$(PackRepoDir)\atmel\AVR-Dx_DFP\1.10.114\gcc\dev\avr128db48"

# D:\IDEs\ArmelStudio\7.0\toolchain\avr8\avr8-gnu-toolchain\avr\include
# D:\IDEs\ArmelStudio\7.0\toolchain\avr8\avr8-gnu-toolchain\lib\gcc\avr\5.4.0\include
# D:\IDEs\ArmelStudio\7.0\toolchain\avr8\avr8-gnu-toolchain\lib\gcc\avr\5.4.0\include-fixed

function(add_avr_target_properties TARGET_NAME)

# __AVR128DB28__

target_compile_definitions(
    ${TARGET_NAME} PRIVATE
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:ASM>>:DEBUG>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:DEBUG>"
    # "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:__AVR128DB28__>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:DEBUG>"
    # "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:__AVR128DB28__>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:F_CPU=16000000UL>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:CLOCK=CLKHT,TA0,CLKNOOUT>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:DIOD=PB,3,INV>"
    # "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:USE_NUCLEO_64>"
    # "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:USE_HAL_DRIVER>"
    # "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:STM32G474xx>"
    # "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:USE_NUCLEO_64>"
    # "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:USE_HAL_DRIVER>"
    # "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:STM32G474xx>"
)

target_include_directories(
    ${TARGET_NAME} PRIVATE
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:D:/IDEs/ArmelStudio/7.0/packs/atmel/AVR-Dx_DFP/1.10.114/include>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/_I>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:c:/AVR/_AVR>"
    # "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:D:/IDEs/ArmelStudio/7.0/toolchain/avr8/avr8-gnu-toolchain/avr/include>"
    # "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:D:/IDEs/ArmelStudio/7.0/toolchain/lib/gcc/avr/5.4.0/include>"
    # "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:D:/IDEs/ArmelStudio/7.0/toolchain/lib/gcc/avr/5.4.0/include-fixed>"
    # "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:D:/IDEs/ArmelStudio/7.0/toolchain/avr8/avr8-gnu-toolchain/avr/include>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:D:/IDEs/ArmelStudio/7.0/packs/atmel/AVR-Dx_DFP/1.10.114/include>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:${PROJECT_SOURCE_DIR}/_I>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:c:/AVR/_AVR>"
    # "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:D:/IDEs/ArmelStudio/7.0/toolchain/avr8/avr8-gnu-toolchain/avr/include>"
    # "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:D:/IDEs/ArmelStudio/7.0/toolchain/lib/gcc/avr/5.4.0/include>"
    # "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:D:/IDEs/ArmelStudio/7.0/toolchain/lib/gcc/avr/5.4.0/include-fixed>"
    # "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:D:/IDEs/ArmelStudio/7.0/toolchain/avr8/avr8-gnu-toolchain/avr/include>"
    # "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Core\\Inc>"
    # "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:C:/Users/User/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Drivers/STM32G4xx_HAL_Driver/Inc>"
    # "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:C:/Users/User/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Drivers/STM32G4xx_HAL_Driver/Inc/Legacy>"
    # "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:C:/Users/User/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Drivers/BSP/STM32G4xx_Nucleo>"
    # "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:C:/Users/User/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Drivers/CMSIS/Device/ST/STM32G4xx/Include>"
    # "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:C:/Users/User/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Drivers/CMSIS/Include>"
    # "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:${PROJECT_SOURCE_DIR}/Core\\Inc>"
    # "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:C:/Users/User/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Drivers/STM32G4xx_HAL_Driver/Inc>"
    # "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:C:/Users/User/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Drivers/STM32G4xx_HAL_Driver/Inc/Legacy>"
    # "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:C:/Users/User/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Drivers/BSP/STM32G4xx_Nucleo>"
    # "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:C:/Users/User/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Drivers/CMSIS/Device/ST/STM32G4xx/Include>"
    # "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:C:/Users/User/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Drivers/CMSIS/Include>"
)

target_compile_options(
    ${TARGET_NAME} PRIVATE
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:ASM>>:-g3>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:-g3>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:-g3>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:ASM>>:-g0>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:-g0>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:-g0>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:-Os>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:-Os>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:-Os>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:-Os>"
    # "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:>"
    # "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:>"
    # "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:>"
    # "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:>"
    # "$<$<CONFIG:Debug>:-mcpu=cortex-m4>"
    # "$<$<CONFIG:Debug>:-mfpu=fpv4-sp-d16>"
    # "$<$<CONFIG:Debug>:-mfloat-abi=hard>"
    # "$<$<NOT:$<CONFIG:Debug>>:-mcpu=cortex-m4>"
    # "$<$<NOT:$<CONFIG:Debug>>:-mfpu=fpv4-sp-d16>"
    # "$<$<NOT:$<CONFIG:Debug>>:-mfloat-abi=hard>"
)

target_link_libraries(
    ${TARGET_NAME} PRIVATE
)

target_link_directories(
    ${TARGET_NAME} PRIVATE
)

# -Wl,-Map="$(OutputFileName).map" 
# -Wl,--start-group 
# -Wl,-lm  
# -Wl,--end-group 
# -Wl,--gc-sections 
# -mmcu=avr128db48 -B "D:\IDEs\ArmelStudio\7.0\Packs\atmel\AVR-Dx_DFP\1.10.114\gcc\dev\avr128db48" 

target_link_options(
    ${TARGET_NAME} PRIVATE
    # "$<$<CONFIG:Debug>:-Wl,-Map=\"$(OutputFileName).map\""
    "$<$<CONFIG:Debug>:-Wl,--start-group>"
    "$<$<CONFIG:Debug>:-Wl,-lm>"
    "$<$<CONFIG:Debug>:-Wl,--end-group>"
    "$<$<CONFIG:Debug>:-Wl,--gc-sections>"
    "$<$<CONFIG:Debug>:-mmcu=avr128db48>"
    # "$<$<NOT:$<CONFIG:Debug>>:-mcpu=cortex-m4>"
    # "$<$<NOT:$<CONFIG:Debug>>:-mfpu=fpv4-sp-d16>"
    # "$<$<NOT:$<CONFIG:Debug>>:-mfloat-abi=hard>"
    # -T
    # "$<$<CONFIG:Debug>:${PROJECT_SOURCE_DIR}/STM32G474RETX_FLASH.ld>"
    # "$<$<NOT:$<CONFIG:Debug>>:${PROJECT_SOURCE_DIR}/STM32G474RETX_FLASH.ld>"
)

# C:\AVR\_AVR\Indicator.cpp

# C:\AVR\_AVR\protected_io.S

# main.cpp

# packer.cpp


target_sources(
    ${TARGET_NAME} PRIVATE
    "C:/AVR/_AVR/Indicator.cpp"
    "C:/AVR/_AVR/protected_io.S"
    "main.cpp"
    "packer.cpp"
    # "Core\\Startup\\startup_stm32g474retx.s"
)

add_custom_command(
    TARGET ${TARGET_NAME} POST_BUILD
    COMMAND ${CMAKE_SIZE} $<TARGET_FILE:${TARGET_NAME}>
)

add_custom_command(
    TARGET ${TARGET_NAME} POST_BUILD
    COMMAND ${CMAKE_OBJCOPY} -O ihex
    $<TARGET_FILE:${TARGET_NAME}> ${TARGET_NAME}.hex
)

add_custom_command(
    TARGET ${TARGET_NAME} POST_BUILD
    COMMAND ${CMAKE_OBJCOPY} -O binary
    $<TARGET_FILE:${TARGET_NAME}> ${TARGET_NAME}.bin
)

endfunction()